---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loadtester-oauth2
  namespace: loadtester
spec:
  ingressClassName: nginx
  rules:
    - host: loadtester.127.0.0.1.nip.io
      http:
        paths:
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: oauth2-proxy
                port:
                  number: 4180

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loadtester
  namespace: loadtester
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "http://oauth2-proxy.keycloak.svc.cluster.local:4180/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "http://loadtester.127.0.0.1.nip.io/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-snippet: |
      proxy_set_header Host loadtester.127.0.0.1.nip.io;
spec:
  ingressClassName: nginx
  rules:
    - host: loadtester.127.0.0.1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: loadtester
                port:
                  number: 80