apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loadtester
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: loadtester.127.0.0.1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: loadtester
                port:
                  number: 80