apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
          args:
            - --provider=oidc
            - --client-id=loadtester-client
            - --oidc-issuer-url=http://keycloak.127.0.0.1.nip.io/realms/loadtester-realm
            - --skip-oidc-discovery=true
            - --redeem-url=http://keycloak.keycloak.svc.cluster.local/realms/loadtester-realm/protocol/openid-connect/token
            - --validate-url=http://keycloak.keycloak.svc.cluster.local/realms/loadtester-realm/protocol/openid-connect/userinfo
            - --oidc-jwks-url=http://keycloak.keycloak.svc.cluster.local/realms/loadtester-realm/protocol/openid-connect/certs
            - --login-url=http://keycloak.127.0.0.1.nip.io/realms/loadtester-realm/protocol/openid-connect/auth
            - --insecure-oidc-skip-issuer-verification=true
            - --skip-jwt-bearer-tokens=true
            - --insecure-oidc-allow-unverified-email=true
            - --redirect-url=http://loadtester.127.0.0.1.nip.io/oauth2/callback
            - --cookie-domain=loadtester.127.0.0.1.nip.io
            - --whitelist-domain=.127.0.0.1.nip.io
            - --insecure-oidc-allow-unverified-email=true
            - --http-address=0.0.0.0:4180
            - --email-domain=*
            - --cookie-secure=false
            - --upstream=static://200
            - --reverse-proxy=true
          env:
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-credentials
                  key: CLIENT_SECRET
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-credentials
                  key: OAUTH2_COOKIE_SECRET
          ports:
            - containerPort: 4180
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy
  namespace: keycloak
spec:
  ports:
    - port: 4180
      targetPort: 4180
      name: http
  selector:
    app: oauth2-proxy
