apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-config
  namespace: keycloak
data:
  loadtester-realm.json: |
    {
      "realm": "loadtester-realm",
      "enabled": true,
      "clients": [
        {
          "clientId": "loadtester-client",
          "enabled": true,
          "publicClient": false,
          "secret": "${env.CLIENT_SECRET}",
          "redirectUris": [
            "http://loadtester.127.0.0.1.nip.io/oauth2/callback"
          ],
          "webOrigins": [
            "http://loadtester.127.0.0.1.nip.io"
          ],
          "standardFlowEnabled": true
        }
      ],
      "users": [
        {
          "username": "devuser",
          "enabled": true,
          "credentials": [
            {
              "type": "password",
              "value": "${env.DEVUSER_PASSWORD}",
              "temporary": false
            }
          ]
        }
      ]
    }